### ISSUE TITLE
Bug with middle moves

### ISSUE THREAD

**Issue by vlad-gev** [hkociemba/RubiksCube-OptimalSolver#1]
Seems to have a bug with middle(F2 B2 L2 D2 R2 U2) moves.
These strings would return an error "second cube Error: Wrong edge and corner parity":
UUULLLUUURURRURRURFFFFFFFFFDDDRRRDDDLDLLDLLDLBBBBBBBBB
UFUUFUUFURRRRRRRRRFDFFDFFDFDBDDBDDBDLLLLLLLLLBUBBUBBUB
UUUUUUUUURRRFFFRRRFFFLLLFFFDDDDDDDDDLLLBBBLLLBBBRRRBBB
UUURRRUUURDRRDRRDRFFFFFFFFFDDDLLLDDDLULLULLULBBBBBBBBB
UBUUBUUBURRRRRRRRRFUFFUFFUFDFDDFDDFDLLLLLLLLLBDBBDBBDB
UUUUUUUUURRRBBBRRRFFFRRRFFFDDDDDDDDDLLLFFFLLLBBBLLLBBB

**Comment by hkociemba** [comment]
Your first string starts with UUULLLUUU. This defines the colors of the U-face. But the center facelet you define as L. This is impossible/wrong since it has to be U all the time since the center color never changes. Slice moves are not allowed at all in the face turn metric. F2 B2 L2 D2 R2 U2 are 180° rotations of the outer faces. Using the slice turn metric would need different pruning tables, different move  tables etc.

**Comment by vlad-gev** [comment]
Got it, it was not clear before, but bit sad that "middle" turn not allowed. Thank you!
